insert into Customers (CustomerID, CompanyName, Address, City) values (1, 'Twiyo', '1 Mockingbird Trail', 'Březová nad Svitavou');
insert into Customers (CustomerID, CompanyName, Address, City) values (2, 'Voonix', '735 Di Loreto Terrace', 'Novogornyy');
insert into Customers (CustomerID, CompanyName, Address, City) values (3, 'Oyoba', '1803 Vahlen Point', 'Neiba');
insert into Customers (CustomerID, CompanyName, Address, City) values (4, 'Skaboo', '81 Bultman Junction', 'Dougang');
insert into Customers (CustomerID, CompanyName, Address, City) values (5, 'Izio', '497 Graceland Pass', 'Enskede');
insert into Customers (CustomerID, CompanyName, Address, City) values (6, 'Devify', '402 Basil Trail', 'Maodian');
insert into Customers (CustomerID, CompanyName, Address, City) values (7, 'Bubbletube', '1 Mayfield Point', 'Gharavŭtí');
insert into Customers (CustomerID, CompanyName, Address, City) values (8, 'Gabcube', '796 Forster Road', 'Gulonggang');
insert into Customers (CustomerID, CompanyName, Address, City) values (9, 'Meetz', '6051 Fairfield Street', 'Zhishan');
insert into Customers (CustomerID, CompanyName, Address, City) values (10, 'Skipstorm', '5 Artisan Drive', 'Potrerillos');
insert into Customers (CustomerID, CompanyName, Address, City) values (11, 'Topiczoom', '09 Lakewood Gardens Hill', 'Tamontaka');
insert into Customers (CustomerID, CompanyName, Address, City) values (12, 'Oodoo', '4 Lawn Drive', 'Gabú');
insert into Customers (CustomerID, CompanyName, Address, City) values (13, 'Jatri', '10503 Moose Trail', 'Campana');
insert into Customers (CustomerID, CompanyName, Address, City) values (14, 'Jatri', '45198 7th Alley', 'Pierzchnica');
insert into Customers (CustomerID, CompanyName, Address, City) values (15, 'Riffwire', '4519 Ridgeway Street', 'Taiping');
insert into Customers (CustomerID, CompanyName, Address, City) values (16, 'Fliptune', '02374 Lotheville Way', 'Dordrecht');
insert into Customers (CustomerID, CompanyName, Address, City) values (17, 'Jabbersphere', '64712 Laurel Drive', 'Gushui');
insert into Customers (CustomerID, CompanyName, Address, City) values (18, 'Rhynoodle', '4016 Pankratz Street', 'La Estancia');
insert into Customers (CustomerID, CompanyName, Address, City) values (19, 'Lazzy', '10127 Mcguire Park', 'Pedro Leopoldo');
insert into Customers (CustomerID, CompanyName, Address, City) values (20, 'Twitterlist', '190 Victoria Pass', 'Hadyach');
insert into Customers (CustomerID, CompanyName, Address, City) values (21, 'Leexo', '847 6th Park', 'Gonghe');
insert into Customers (CustomerID, CompanyName, Address, City) values (22, 'Zoomlounge', '3 Michigan Alley', 'Zhihe');
insert into Customers (CustomerID, CompanyName, Address, City) values (23, 'Aimbo', '75 Kensington Crossing', 'Saidpur');
insert into Customers (CustomerID, CompanyName, Address, City) values (24, 'Rhybox', '102 Kropf Hill', 'Priozërsk');
insert into Customers (CustomerID, CompanyName, Address, City) values (25, 'Babbleopia', '52368 Chinook Lane', 'Béziers');
insert into Customers (CustomerID, CompanyName, Address, City) values (26, 'Eabox', '5877 Artisan Junction', 'Bălţi');
insert into Customers (CustomerID, CompanyName, Address, City) values (27, 'Bubblebox', '0 Columbus Parkway', 'Seremban');
insert into Customers (CustomerID, CompanyName, Address, City) values (28, 'Tavu', '49 Elgar Way', 'Las Flores');
insert into Customers (CustomerID, CompanyName, Address, City) values (29, 'Thoughtworks', '8 Arkansas Terrace', 'Longquan');
insert into Customers (CustomerID, CompanyName, Address, City) values (30, 'Meedoo', '34690 Homewood Junction', 'Malaga');
insert into Customers (CustomerID, CompanyName, Address, City) values (31, 'Ainyx', '39686 Hanson Plaza', 'Perm');
insert into Customers (CustomerID, CompanyName, Address, City) values (32, 'Tagopia', '77 Oak Valley Park', 'Fermoy');
insert into Customers (CustomerID, CompanyName, Address, City) values (33, 'Browseblab', '29 South Lane', 'Lahad Datu');
insert into Customers (CustomerID, CompanyName, Address, City) values (34, 'Jayo', '3 Manufacturers Hill', 'Cungkal');
insert into Customers (CustomerID, CompanyName, Address, City) values (35, 'Realfire', '264 Katie Court', 'An Lão');
insert into Customers (CustomerID, CompanyName, Address, City) values (36, 'Skyble', '50137 Manitowish Road', 'Opi');
insert into Customers (CustomerID, CompanyName, Address, City) values (37, 'Blognation', '5655 Marquette Terrace', 'Santi Suk');
insert into Customers (CustomerID, CompanyName, Address, City) values (38, 'Youopia', '80033 Butterfield Lane', 'Kanganpur');
insert into Customers (CustomerID, CompanyName, Address, City) values (39, 'Zooxo', '00 Bowman Alley', 'Shangjiangxu');
insert into Customers (CustomerID, CompanyName, Address, City) values (40, 'Meevee', '50 Barby Street', 'Igreja');
insert into Customers (CustomerID, CompanyName, Address, City) values (41, 'Janyx', '6 Ohio Trail', 'Tiechanggou');
insert into Customers (CustomerID, CompanyName, Address, City) values (42, 'Tazz', '5352 Toban Lane', 'Gielniów');
insert into Customers (CustomerID, CompanyName, Address, City) values (43, 'Dabshots', '65 Doe Crossing Avenue', 'Järfälla');
insert into Customers (CustomerID, CompanyName, Address, City) values (44, 'Edgeclub', '680 Dixon Crossing', 'Göteborg');
insert into Customers (CustomerID, CompanyName, Address, City) values (45, 'Kimia', '8458 Spaight Point', 'Shaowu');
insert into Customers (CustomerID, CompanyName, Address, City) values (46, 'Youbridge', '36 Lighthouse Bay Crossing', 'Acacías');
insert into Customers (CustomerID, CompanyName, Address, City) values (47, 'Quimm', '3 Sullivan Junction', 'Minante Segundo');
insert into Customers (CustomerID, CompanyName, Address, City) values (48, 'Meevee', '71 Sunbrook Crossing', 'Āshkhāneh');
insert into Customers (CustomerID, CompanyName, Address, City) values (49, 'Dabshots', '40 Dawn Pass', 'Hancheng');
insert into Customers (CustomerID, CompanyName, Address, City) values (50, 'Edgeblab', '47249 High Crossing Court', 'Lanuza');
insert into Customers (CustomerID, CompanyName, Address, City) values (51, 'Jaxnation', '995 Prentice Drive', 'Porto-Novo');
insert into Customers (CustomerID, CompanyName, Address, City) values (52, 'Voomm', '055 Lotheville Avenue', 'Bulog');
insert into Customers (CustomerID, CompanyName, Address, City) values (53, 'Yodoo', '70 Grim Terrace', 'Tân Trụ');
insert into Customers (CustomerID, CompanyName, Address, City) values (54, 'Mynte', '54 Eagle Crest Junction', 'Purda');
insert into Customers (CustomerID, CompanyName, Address, City) values (55, 'Thoughtstorm', '7134 Becker Center', 'Łobodno');
insert into Customers (CustomerID, CompanyName, Address, City) values (56, 'Yodel', '992 Hagan Court', 'Vila Nova da Baronia');
insert into Customers (CustomerID, CompanyName, Address, City) values (57, 'Roomm', '463 Stoughton Alley', 'Saint-Priest');
insert into Customers (CustomerID, CompanyName, Address, City) values (58, 'Plajo', '4625 Menomonie Crossing', 'Behābād');
insert into Customers (CustomerID, CompanyName, Address, City) values (59, 'Quire', '6 Dakota Parkway', 'Nichinan');
insert into Customers (CustomerID, CompanyName, Address, City) values (60, 'Flipbug', '32 Grayhawk Way', 'Pražmo');
insert into Customers (CustomerID, CompanyName, Address, City) values (61, 'Devshare', '362 Johnson Court', 'Shuanglong');
insert into Customers (CustomerID, CompanyName, Address, City) values (62, 'Twitterworks', '071 Katie Court', 'Fermoy');
insert into Customers (CustomerID, CompanyName, Address, City) values (63, 'Jabbersphere', '916 Schmedeman Parkway', 'L’vovskiy');
insert into Customers (CustomerID, CompanyName, Address, City) values (64, 'Dabfeed', '04169 Raven Crossing', 'Manzini');
insert into Customers (CustomerID, CompanyName, Address, City) values (65, 'Topicstorm', '9 Jay Trail', 'Embarcación');
insert into Customers (CustomerID, CompanyName, Address, City) values (66, 'Pixoboo', '1047 Heffernan Trail', 'Pasirpengarayan');
insert into Customers (CustomerID, CompanyName, Address, City) values (67, 'Midel', '8138 Talisman Avenue', 'Esperança');
insert into Customers (CustomerID, CompanyName, Address, City) values (68, 'Leenti', '80 Arkansas Road', 'Ramat Yishay');
insert into Customers (CustomerID, CompanyName, Address, City) values (69, 'Kanoodle', '7638 Towne Road', 'Samoš');
insert into Customers (CustomerID, CompanyName, Address, City) values (70, 'Meeveo', '44 Starling Hill', 'Tejar');
insert into Customers (CustomerID, CompanyName, Address, City) values (71, 'Mita', '18 Sauthoff Road', 'Lae');
insert into Customers (CustomerID, CompanyName, Address, City) values (72, 'Zooxo', '2 Delladonna Pass', 'Bolikhan');
insert into Customers (CustomerID, CompanyName, Address, City) values (73, 'InnoZ', '7130 Hudson Point', 'Pambuhan');
insert into Customers (CustomerID, CompanyName, Address, City) values (74, 'Teklist', '94 Hagan Hill', 'Quxi');
insert into Customers (CustomerID, CompanyName, Address, City) values (75, 'Babbleblab', '847 Little Fleur Court', 'Aizkraukle');
insert into Customers (CustomerID, CompanyName, Address, City) values (76, 'Trudeo', '5 Killdeer Parkway', 'Thanh Khê');
insert into Customers (CustomerID, CompanyName, Address, City) values (77, 'Edgeblab', '11 Fieldstone Alley', 'Luoyang');
insert into Customers (CustomerID, CompanyName, Address, City) values (78, 'Tagopia', '54470 Rusk Point', 'Laoxialu');
insert into Customers (CustomerID, CompanyName, Address, City) values (79, 'Fivechat', '65414 Mockingbird Crossing', 'Guli');
insert into Customers (CustomerID, CompanyName, Address, City) values (80, 'Cogibox', '22510 Marquette Junction', 'San Isidro');
insert into Customers (CustomerID, CompanyName, Address, City) values (81, 'Quamba', '07462 Corben Point', 'Gabao');
insert into Customers (CustomerID, CompanyName, Address, City) values (82, 'Kayveo', '7 Karstens Place', 'Alcalá');
insert into Customers (CustomerID, CompanyName, Address, City) values (83, 'Youbridge', '80937 Claremont Court', 'Xintai');
insert into Customers (CustomerID, CompanyName, Address, City) values (84, 'Roodel', '16797 8th Road', 'Longgang');
insert into Customers (CustomerID, CompanyName, Address, City) values (85, 'Abatz', '2062 Fairview Circle', 'Boca Suno');
insert into Customers (CustomerID, CompanyName, Address, City) values (86, 'Blogtags', '62393 Oak Valley Avenue', 'Xidajie');
insert into Customers (CustomerID, CompanyName, Address, City) values (87, 'Youspan', '90 Harper Trail', 'Maodao');
insert into Customers (CustomerID, CompanyName, Address, City) values (88, 'Nlounge', '107 Hooker Alley', 'Fort McMurray');
insert into Customers (CustomerID, CompanyName, Address, City) values (89, 'Topicstorm', '71454 Prairieview Place', 'Cimanglid');
insert into Customers (CustomerID, CompanyName, Address, City) values (90, 'Trudoo', '1 Maple Terrace', 'Gosë e Madhe');
insert into Customers (CustomerID, CompanyName, Address, City) values (91, 'Tagfeed', '2 Helena Center', 'Murtajih');
insert into Customers (CustomerID, CompanyName, Address, City) values (92, 'Kazu', '773 Lerdahl Road', 'Huoxian');
insert into Customers (CustomerID, CompanyName, Address, City) values (93, 'Gabtype', '6 Jay Pass', 'Göteborg');
insert into Customers (CustomerID, CompanyName, Address, City) values (94, 'Agivu', '4 Swallow Alley', 'Nanjing');
insert into Customers (CustomerID, CompanyName, Address, City) values (95, 'Yacero', '4 Armistice Circle', 'Rostokino');
insert into Customers (CustomerID, CompanyName, Address, City) values (96, 'Tavu', '99 Clemons Pass', 'Silab');
insert into Customers (CustomerID, CompanyName, Address, City) values (97, 'Yabox', '0 Daystar Way', 'Wufeng');
insert into Customers (CustomerID, CompanyName, Address, City) values (98, 'Camido', '46397 Hanover Avenue', 'Jiaoshi');
insert into Customers (CustomerID, CompanyName, Address, City) values (99, 'Quamba', '8592 Grasskamp Terrace', 'Mazār-e Sharīf');
insert into Customers (CustomerID, CompanyName, Address, City) values (100, 'Dabfeed', '99435 Mendota Point', 'Taichung');
